export * from './generalInfo/InfoCard'
export * from './categoryInfo/CategoryInfo'
export * from './bestSellingGames/BestSellingGamesChart'
export * from './listInfo/LatestGamesAdded'
export * from './generalInfo/GeneralInfo'
export * from './salesPerMonth/SalesPerMonth'
